//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MorePractice
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reception
    {
        public System.Guid ID { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        public System.String RecTime { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        public bool EmailNotification { get; set; }
        public System.Guid ID_Pet { get; set; }
        public System.Guid ID_Service { get; set; }
        public System.Guid ID_Doctor { get; set; }

        [ForeignKey("ID_Doctor")]
        public virtual Doctor Doctor { get; set; }
        [ForeignKey("ID_Pet")]
        public virtual Pet Pet { get; set; }
        [ForeignKey("ID_Service")]
        public virtual Service Service { get; set; }
    }
}
