//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MorePractice
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VetClinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VetClinic()
        {
            this.Doctor = new HashSet<Doctor>();
        }
    
        public System.Guid ID { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        [MaxLength(20, ErrorMessage = "Слишком много символов.")]
        public string Clinic { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        [MaxLength(20, ErrorMessage = "Слишком много символов.")]
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}
